services:
  - type: web
    name: olimplider
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /login.html
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false